language: node_js
node_js: lts/*
before_install:
  - sudo apt-get -y install calibre #for pdf, ebook
script: npm run publish
before_deploy:
  - touch _book/.nojekyll
  - if [ -n $CNAME ] ; then echo $CNAME > _book/CNAME ; fi #custom domain
deploy:
  provider: pages:git
  edge: true # opt in to dpl v2
  local_dir: _book
# safelist
branches:
  only:
  - master
